### ISSUE TITLE
is there an option to output final resault without space serprating rules?

### ISSUE THREAD

**Issue by Ali-00-Ridha** [0xVavaldi/ruleprocessorY#5]
if not, then I realy like such an a option.

output (Currently):
u $1 $2 $3

output (Wishlist):
u$1$2$3

**Comment by 0xVavaldi** [comment]
There is no current way to do it, as we do not have a dynamic specification of delimiter. But it can be adjusted on line 1453 in the current build.

https://github.com/0xVavaldi/ruleprocessorY/blob/main/main.cpp#L1453

````cpp`
        for(auto rules : rule_objects) {
            for(int i = 0; i < rules.size(); i++) {
                rules[i].print();
                if(i != rules.size()-1) {
                    if(hashcat_output) {
                        std::cout << ' '; // hashcat formatting
                    } else {
                        std::cout << '\t'; // RuleProcessorY formatting
                    }
                }
            }
            std::cout << std::endl;
        }
```
