### ISSUE TITLE
update error when -r is missing

### ISSUE THREAD

**Issue by Shooter3k** [0xVavaldi/ruleprocessorY#6]
when the -r value isn't specified correctly as in this example, the error should be updated to be more useful. (Perhaps it's not checking for all required parameters?)

ruleprocessorY.exe hashcat-input --hashcat-output --optimize-compare generated.rule dive.rule > modgen.rule
--optimize-compare has automatically enabled --optimize-similar-op.
--optimize-compare will not check the original file.
Rule file error: "" does not exist.

**Comment by 0xVavaldi** [comment]
Fixed in 656bf25adaf64edd7e29df4ebabe884cc54048b9
