### ISSUE TITLE
Thank you and Request

### ISSUE THREAD

**Issue by Binary-Bear** [0xVavaldi/ruleprocessorY#7]
Hello 0xVavaldi

Firstly thank you very much for ruleprocessorY.exe! Not only is ruleprocessorY.exe a great idea but it also works well.

I wonder if you would please consider two requests?

1.  Please would you enable the user to output Rule:Result to a text file?  This would allow the user to experiment with rules and see the result of each in an easy way.

This option would also allow the user to identify problems, undesirable outputs or bad rules.
An example using the new option "--show-rule"

`"!ruleprocessorY.exe!" -w passwordlist.txt -r testrule.rule --hashcat-input --show-rule --delimiter : >outputlist.txt`

The desired output.txt would be:

$1:password1
$1$2$3:password123
^1:1password
u:PASSWORD
d:passwordpassword
etc...

2.  Please would you enable the user to output the --optimize-debug to a separate file whilst simultaneously cleaning their rule lists?
An example.

`ruleprocessorY.exe --optimize-all --hashcat-input --optimize-debug debugfile.txt -r testrule.rule >>testrule_optimised.rule`

The desired output would be:

testrule_optimised.rule (Containing only optimised rules and no debug information)
debugfile.txt (Containing only debug information)

Thank you once again 0xVavaldi for creating ruleprocessorY.exe and especially for sharing it!

**Comment by 0xVavaldi** [comment]
Glad you're enjoying the tool. I've added both of the requests in https://github.com/0xVavaldi/ruleprocessorY/commit/3103a9b03115f9433819e21c3e2ae9a013c87090.

You can specify the delimiter to use with --show-rule and it will use that delimiter for each rule. They can not be concatenated due to rules like "s/abc/def" and $$$$ (appending $ 3x) being valid rules vs "$$      $$" being append $ 2x. You can split on the 'last delimiter' to properly separate the passwords. It chooses tab as the default separator. If you have a suggestion for a better approach / output, I am open to suggestions.

--optimize-debug will not output to STDOUT by default and will output to a file if specified.

**Comment by 0xVavaldi** [comment]
Could you please provide the full command you are using for this, and the outputs of the two files?

**Comment by 0xVavaldi** [comment]
With latest changes:
```
root@Development:~/Projects/ruleprocessorY# cat test.rule
$1]
^1

root@Development:~/Projects/ruleprocessorY# ./ruleprocessorY --optimize-all --hashcat-input --hashcat-output --delimiter --optimize-debug debug.txt -r test.rule >>clean.rule
You did not specify a delimiter. Using the default delimiter.
Enabled Debugging
Started parsing rules
Completed parsing rules
Starting no-op
[======================================================================] 100% (2 / 2)
no-op: 0 sec

Starting same-op
[======================================================================] 100% (1 / 1)
Finalizing same-op... please wait, this can take a while
same-op: 1 sec

Starting similar-op
Pregenerating data. Estimated Memory usage: 0.07MB.
Memory usage can start off a lot higher than expected, especially if specifying a wordlist.
Completed Pregenerating Data
[======================================================================] 100% (1 / 1)
Finalizing similar-op
similar-op: 0 sec
Total Time: 1 sec
Reorganizing rules

Completed optimization
Comments (untouched): 0
Rules Before: 2
Rules After: 1
no-op Removed: 1
same-op Optimized: 0
similar-op Removed: 0
Invalid Removed: 0
root@Development:~/Projects/ruleprocessorY# cat debug.txt
Deleted:        $1      ]
root@Development:~/Projects/ruleprocessorY# cat clean.rule
^1
```
