### ISSUE TITLE
Request: Format Rules Only

### ISSUE THREAD

**Issue by Binary-Bear** [0xVavaldi/ruleprocessorY#8]
Format Rules

Please could there be an option to only format the rules? (not carry out any optimizations).

Example. (--format-rules)

`ruleprocessorY.exe --format-rules --delimiter " " -r "rules.rule" >>"formatted_rules.rule"`

The above would convert:

^x^i^f^e^r^p^_^t^s^e^t
to
^x ^i ^f ^e ^r ^p ^_ ^t ^s ^e ^t

Alternatively:

`ruleprocessorY.exe --format-rules --delimiter -r "rules.rule" >>"formatted_rules.rule"`

The above would convert:

^x ^i ^f ^e ^r ^p ^_ ^t ^s ^e ^t
to
^x^i^f^e^r^p^_^t^s^e^t

Thank you.

**Comment by 0xVavaldi** [comment]
Added

https://github.com/0xVavaldi/ruleprocessorY/commit/bd36f2061e7ef42836a55227b2a5ec497af005ad#diff-608d8de3fba954c50110b6d7386988f27295de845e9d7174e40095ba5efcf1bbR1499
